### ISSUE TITLE
Unable to get href attribute

### ISSUE THREAD

**Issue by wealthr** [kaliiiiiiiiii/Selenium-Profiles#110]
Code works well with selenium and print's out the attribute, but with selenium-profile i get "none" printed out for the url, but prints out the h3 element text.

Here's My Code : `from selenium_profiles.webdriver import Chrome
from selenium_profiles.profiles import profiles
from selenium_driverless.webdriver import ChromeOptions
from selenium_driverless.types.by import By

profile = profiles.Windows()  # or .Android
options = ChromeOptions()
# options.add_argument("--headless=new")
driver = Chrome(profile, options=options, driverless_options=True)

# get url
driver.get('https://www.google.com/search?q=python')  # test fingerprint

# Find all h3 elements within search results
h3_elements = driver.find_elements(By.CSS_SELECTOR, 'h3')

# Print the text of each h3 element
for h3_element in h3_elements:
    url = h3_element.get_attribute('href')
    print(h3_element.text)
    print(url)

driver.quit()  # Execute on the End!
`

**Comment by kaliiiiiiiiii** [comment]
@wealthr 
please
1. Provide your code in the following format:
```python
# some code ...
```
2. Update your driverless version & try again.

**Comment by wealthr** [comment]
hello @kaliiiiiiiiii

**Comment by kaliiiiiiiiii** [comment]
> hello @kaliiiiiiiiii

Great, thanks!
I'll test your code & lyk:)

**Comment by wealthr** [comment]
Alright, thanks

**Comment by wealthr** [comment]
any update please @kaliiiiiiiiii

**Comment by kaliiiiiiiiii** [comment]
That's due to how selenium-driverless works. Let's close this issue, as driverless is not scope of this project.
