### ISSUE TITLE
UNABLE TO LOAD PACKED EXTENSION

### ISSUE THREAD

**Issue by wealthr** [kaliiiiiiiiii/Selenium-Profiles#112]
My code:
```python

from selenium_profiles.webdriver import Chrome
from selenium_profiles.profiles import profiles
from selenium_driverless.webdriver import ChromeOptions
from selenium_driverless.types.by import By

profile = profiles.Windows()  # or .Android

profile["options"]["extension_paths"] = ['canvas.crx']

options = ChromeOptions()
driver = Chrome(profile, options=options, driverless_options=True)

# get url
driver.get('https://nowsecure.nl#relax')  # test fingerprint
input()

driver.quit()  # Execute on the End!

```

TRACEBACK:
```python

C:\Users\alima\PycharmProjects\pythonProject\venv\Scripts\python.exe C:\Users\alima\PycharmProjects\pythonProject\TEST.py 
Traceback (most recent call last):
  File "C:\Users\alima\PycharmProjects\pythonProject\TEST.py", line 11, in <module>
    driver = Chrome(profile, options=options, driverless_options=True)
  File "C:\Users\alima\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_profiles\webdriver.py", line 109, in __init__
    options_manager = options_handler(options, profile["options"], duplicate_policy=duplicate_policy,
  File "C:\Users\alima\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_profiles\scripts\profiles.py", line 244, in __init__
    self.apply(options_profile)
  File "C:\Users\alima\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_profiles\scripts\profiles.py", line 263, in apply
    self.add_extensions(profile["extension_paths"], adb=profile["adb"])
  File "C:\Users\alima\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_profiles\scripts\profiles.py", line 529, in add_extensions
    self.Options.add_extension(extension_path)
  File "C:\Users\alima\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_driverless\types\options.py", line 415, in add_extension
    raise NotImplementedError()
NotImplementedError
Exception ignored in: <function Chrome.__del__ at 0x00000274C79AB7F0>
Traceback (most recent call last):
  File "C:\Users\alima\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_driverless\webdriver.py", line 503, in __del__
    if self._started:
  File "C:\Users\alima\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_driverless\sync\webdriver.py", line 31, in __getattribute__
    res = super().__getattribute__(item)
AttributeError: 'Chrome' object has no attribute '_started'

Process finished with exit code 1
```

**Comment by kaliiiiiiiiii** [comment]
@wealthr This is a warning. Please read the error-message fully through before opening an issue. 

If you keep opening arbitrary issues, I might have to restrict you from doing so!

**Comment by wealthr** [comment]
I'm sorry about that, i saw where you shared the method for packed extension, so i tried it and had to raise the issue because it didn't work

**Comment by kaliiiiiiiiii** [comment]
> I'm sorry about that, i saw where you shared the method for packed extension, so i tried it and had to raise the issue because it didn't work

yep, that's because it only works with an **unpacked extension**

**Comment by wealthr** [comment]
i tried running same code above after upgrading my selenium-profile and driverless to the updated version.

i get this error while trying to quit the browser "
C:\Users\wealth
\PycharmProjects\vent\venv\lib\site-packages\selenium_profiles\webdriver.py:211: RuntimeWarning: coroutine 'Chrome.quit' was never awaited
  super().quit()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Process finished with exit code 0
"

**Comment by kaliiiiiiiiii** [comment]
> i tried running same code above after upgrading my selenium-profile and driverless to the updated version.
> 
> i get this error while trying to quit the browser " C:\Users\wealth \PycharmProjects\vent\venv\lib\site-packages\selenium_profiles\webdriver.py:211: RuntimeWarning: coroutine 'Chrome.quit' was never awaited super().quit() RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> 
> Process finished with exit code 0 "

yep this ideed is an issue with the new driverless & profiles. Atm, there's no fix for that

**Comment by wealthr** [comment]
okay, is there any other way to close the browser window?, so multiple windows don't have to open on a while loop when an exception occurs

**Comment by kaliiiiiiiiii** [comment]
> okay, is there any other way to close the browser window?, so multiple windows don't have to open on a while loop when an exception occurs

what you can to is just to use the sync version of driverless without profiles

**Comment by wealthr** [comment]
I need profiles, i will just wait for your update that resolves this

**Comment by kaliiiiiiiiii** [comment]
> I need profiles, i will just wait for your update that resolves this

Yeah unfortanely, solving this one is real hard:/
