### ISSUE TITLE
how can i use seleniumbase with seleniumprofiles instead of selenium wire ?

### ISSUE THREAD

**Issue by pythondeveloperz** [kaliiiiiiiiii/Selenium-Profiles#115]
how can i use seleniumbase with seleniumprofiles instead of selenium wire ?
https://github.com/seleniumbase/SeleniumBase

**Comment by kaliiiiiiiiii** [comment]
No you cannot.
Also, If you continue opening issues without an actual bug, I'll have to block you from interacting  with this reporitory.
