### ISSUE TITLE
Does not work with implicit waits or WebDriverWait

### ISSUE THREAD

**Issue by ChrisHelmsC** [kaliiiiiiiiii/Selenium-Profiles#118]
**Describe the bug**
The driver will not work as an input to WebDriverWait, which does not wait but instantly errors out. Additionally, `driver.implicitly_wait(10)` does not appear to exist. Time.sleep() is required to wait for page loads.

**To Reproduce**
```
def configureDriver():
    profile = profiles.Windows() # or .Android
    options = ChromeOptions()
    options.add_argument("--headless=new")
    driver = Chrome(profile, options=options, driverless_options=True)

    # Doesn't exist
    driver.implicitly_wait(10)

    driver.get('https://example.com')

    # Errors instantly
    WebDriverWait(driver, 100).until(EC.visibility_of_element_located(
        (By.ID, 'login-username')))
```

**Expected behavior or error-message**
Driver should support use of WebDriverWait for best practices.

**Environment (please complete the following information):**
 - OS: Windows, Mac
- OS-Version Windows 10
- Browser Chrome
 - Selenium-Profiles Version 2.2.10
 - Selenium Version 4.12.0
 - selenium-driverless Version 1.5.2
 - Python version 3.11.5

**Comment by kaliiiiiiiiii** [comment]
Az stated in the readme, driverless is experimental.
Driverless does not aim to support full compability anymore.
