### ISSUE TITLE
TypeError("'NoneType' object is not iterable") when adding extensions.

### ISSUE THREAD

**Issue by kaliiiiiiiiii** [kaliiiiiiiiii/Selenium-Profiles#15]
When adding a extension using `profile["Options"]["extensions"] = {"extension_paths":[extension_path]}` , [selenium.scripts.profiles](https://github.com/kaliiiiiiiiii/Selenium-Profiles/blob/master/src/selenium_profiles/scripts/profiles.py#L206-L213) thinks that proxy-authentification extension is used, which raises an error.

**Comment by kaliiiiiiiiii** [comment]
Workaround for now to add a extension from directory is:
```python
profile["options"]["option_args"] = ["--load-extension="+extension_path]
```

**Comment by Pingo-v0** [comment]
> Workaround for now to add a extension from directory is:
> 
> ```python
> profile["options"]["option_args"] = ["--load-extension="+extension_path]
> ```

And extension_path corresponds to the directory containing backgound ?

**Comment by kaliiiiiiiiii** [comment]
Usually when adding a extension to Chrome, the user would load it as a compressed `.crx` file. But for making it easy, we can directly load it from a directory.
In this way, we don't need to compress all the files in our extension_directory to a `.crx` file.

**Comment by Pingo-v0** [comment]
It works ! -thanks again 🙏 🙏

**Comment by kaliiiiiiiiii** [comment]
Fixed with https://github.com/kaliiiiiiiiii/Selenium-Profiles/commit/865c0bfb720538f97172c6d352ef6454fb437d72
