### ISSUE TITLE
Modheader doesn't change headers

### ISSUE THREAD

**Issue by kaliiiiiiiiii** [kaliiiiiiiiii/Selenium-Profiles#2]
ModHeader doesn't have an effect when using a Profile

**Comment by kaliiiiiiiiii** [comment]
Maybe edit ModHeader source-code?

**Comment by kaliiiiiiiiii** [comment]
### modheader doesn't get the right permissions when installing with python, manual installation works!
maybe because of that?:

![image](https://user-images.githubusercontent.com/89038706/201314162-b62edefe-d3ab-4ee1-913f-0c745f344f7d.png)

### how to install with right permissions?

**Comment by kaliiiiiiiiii** [comment]
fixed with new [commit](https://github.com/kaliiiiiiiiii/Selenium-Profiles/commit/03045a5845ca658c9ec31956d1ee66427dc8151c)
- updated extension installation for Chrome
- changed "add_headers" to load header profile ==> change headers works now

**Comment by SamPse** [comment]
How can I added extension to my code ? For example ublock origin?

**Comment by kaliiiiiiiiii** [comment]
> How can I added extension to my code ? For example ublock origin?

## TODO: Add extension-autoinstaller as selenium_profiles import
