### ISSUE TITLE
Add the possibility to add custom path to driver object 

### ISSUE THREAD

**Issue by Bolini4** [kaliiiiiiiiii/Selenium-Profiles#21]
I just edited your code to do this :
driver.py
```python
line 20 :     def __init__(self, driverPath= None):
line 30 :         self.driverPath = driverPath
line 87 :             self.driver = webdriver.Chrome(options=self.options, executable_path=self.driverPath)`  # start selenium webdriver
```

I am not very good with github and python but this feature would help me a lot !

EDIT: improved formatting and grammar

**Comment by kaliiiiiiiiii** [comment]
Sure, I absolutely see the point of this.
I'm quite busy, but I'll implement it and at the same time fix some bugs

**Comment by kaliiiiiiiiii** [comment]
Implemented with https://github.com/kaliiiiiiiiii/Selenium-Profiles/commit/b77151a0b4cbe2c35db7f44d0c8c01cd5712e03d
example: 
```python
driver = mydriver.start(profile, uc_driver=False, chrome_binary="C:/Program Files/Google/Chrome/Application/chrome.exe", executable_path= chromedriver.exe)
```

## Feel free to install the new version and test with and without `uc_driver` , then close this issue if it's resolved and maybe give me a star:)

**Comment by Bolini4** [comment]
This solution worked well ! I'm happy to work with your solution !
