### ISSUE TITLE
Detected on Chromium 110

### ISSUE THREAD

**Issue by wmetryka** [kaliiiiiiiiii/Selenium-Profiles#26]
**Describe the bug**

Trying to use Selenium to get through Google Identity Provider and it throws the "unsafe browser" error at me. Seems like it got patched alongside undetected_chromedriver. 

**Environment:**
 - OS: Windows
- OS-Version: 10
- Browser: Chromium 110

**Comment by kaliiiiiiiiii** [comment]
Thanks for your report.
Do you run on headless?
