### ISSUE TITLE
https://www.whatismybrowser.com detects that the device is not mobile

### ISSUE THREAD

**Issue by nradosevic** [kaliiiiiiiiii/Selenium-Profiles#27]
**Describe the bug**
When you select Android platform device and head over to https://www.whatismybrowser.com, it tell you this:

YOUR WEB BROWSER LOOKS LIKE:
Chrome on Linux
BUT IS ANNOUNCING IT'S
[Chrome 105 on Android 11]

**To Reproduce**

```
from selenium_profiles.driver import driver as mydriver
from selenium_profiles.profiles import profiles

from selenium.webdriver.common.by import By


# Start Driver
mydriver = mydriver()
profile = profiles.Android()
driver = mydriver.start(profile, uc_driver=False)  # or .Android

# initialise touch_actions
actions = actions(driver)

driver.get('https://www.whatismybrowser.com')

# quit driver
input('Press ENTER to quit Driver\n')
driver.quit()
```

**Comment by kaliiiiiiiiii** [comment]
Mhh I wonder.. noticed the same issue on Replit some days ago.
- Does `driver.execute_cdp_cmd()` work correctly? (what does `driver.execute_cdp_cmd("Browser.getVersion", {})` return you?
- Chrome Version?
- Chromedriver Version?
- What OS and  OS-Version?

**Comment by nradosevic** [comment]
Yeah that seems to be a bug on https://www.whatismybrowser.com for many Android devices. Got it on my Galaxy S22 too. I will close the issue
