### ISSUE TITLE
window.screen width and height values aren't changed to the profile's emulation values

### ISSUE THREAD

**Issue by nradosevic** [kaliiiiiiiiii/Selenium-Profiles#29]
**Describe the bug**
`window.screen` `width` and `height` values __aren't changed__ to the profile's emulation values. Might actually be undetected chromedriver's fault because it doesn't support `mobileEmulation` experimental option, but anyway would be really meaningful to find a workaround

**To Reproduce**
Run the code from the example, using any profile (Desktop or Android) and check the window.screen values in dev tools

**Expected behavior or error-message**
window.screen width and height values should get the value 

**Environment (please complete the following information):**
 - MacOS
- Monterey
- Google Chrome
- Selenium-Profiles Version 2.2.5

**Comment by nradosevic** [comment]
Actually, it seems that this line `return self.driver.execute_cdp_cmd('Emulation.setDeviceMetricsOverride', emulation)` should do it, for some reason it doesn't

**Comment by nradosevic** [comment]
When I execute this directly on the driver instance after mydriver.start finishes it changes those values

driver.execute_cdp_cmd("Emulation.setDeviceMetricsOverride", {
    "deviceScaleFactor": 3,
    "width": 390,
    "height": 844,
    "screenWidth": 390,
    "screenHeight": 844,
    "mobile": True
})

**Comment by kaliiiiiiiiii** [comment]
> Actually, it seems that this line `return self.driver.execute_cdp_cmd('Emulation.setDeviceMetricsOverride', emulation)` should do it, for some reason it doesn't

Wonder why it doesn't work. Stack trace should be `driver.py==>scripts/profiles.py==>scripts/cdp_tools.py`
Noticed some time ago, that after initializing the driver, I need to wait some time bevore executing all the `cdp_cmd` commands. Solved that in `driver.py` by just getting some url.

**Comment by nradosevic** [comment]
I am puzzled how window.screen values are correct in your case. In my case I found a problem. Problem is that the emulation object in the default profiles is lacking those options: `screenWidth, screenHeight`, because they are needed to set the correct screen size when using `driver.execute_cdp_cmd("Emulation.setDeviceMetricsOverride"`

After adding those to the default profiles, it works for me too

**Comment by AlexPaiva** [comment]
> > I am puzzled how window.screen values are correct in your case. In my case I found a problem. Problem is that the emulation object in the default profiles is lacking those options: `screenWidth, screenHeight`, because they are needed to set the correct screen size when using `driver.execute_cdp_cmd("Emulation.setDeviceMetricsOverride"`
> > After adding those to the default profiles, it works for me too
> 
> Oh I see In that case, I'll implement following in some time:
> 
>     * If the keys don't exist in `profile`, copy fom `height` and `with`
> 
> 
> Also, this likely doesn't have anything to do with with `undetected-chromedriver`. I assuem it's some inconsistency in in the `chrome-developer-protocoll` implementation of chromedriver nur or Chromium

Not sure because I remember on UC discussions people complaining regarding this, but might be as you said so both packages suffer from this

**Comment by kaliiiiiiiiii** [comment]
> > I am puzzled how window.screen values are correct in your case. In my case I found a problem. Problem is that the emulation object in the default profiles is lacking those options: `screenWidth, screenHeight`, because they are needed to set the correct screen size when using `driver.execute_cdp_cmd("Emulation.setDeviceMetricsOverride"`
> > After adding those to the default profiles, it works for me too
> 
> Oh I see In that case, I'll implement following in some time:
> 
> * If the keys don't exist in `profile`, copy fom `height` and `with`
> 
> Also, this likely doesn't have anything to do with with `undetected-chromedriver`. I assuem it's some inconsistency in in the `chrome-developer-protocoll` implementation of chromedriver nur or Chromium

Implemented with https://github.com/kaliiiiiiiiii/Selenium-Profiles/commit/6f259906c6e8035d93753c25622cfb0831d5f272
