### ISSUE TITLE
how to activate cookies

### ISSUE THREAD

**Issue by kSalih54** [kaliiiiiiiiii/Selenium-Profiles#4]
how to activate cookies ?

**Comment by kaliiiiiiiiii** [comment]
Are you asking bout how to add, remove, and read cookies?
Also to add a cookie property for the Profiles?
you can try: https://stackoverflow.com/questions/15058462/how-to-save-and-load-cookies-using-python-selenium-webdriver
didn't test if it works yet tho.

**Comment by kaliiiiiiiiii** [comment]
## Fixed cookies
rewrote cookie functions (https://github.com/kaliiiiiiiiii/Selenium-Profiles/commit/a79132d6f3ec7acf85bca68105e960fe85fcbb40)
see [selenium-docs](https://www.selenium.dev/documentation/webdriver/interactions/cookies/) cookie for usage.
