### ISSUE TITLE
Headless bug in undetected-chromedriver

### ISSUE THREAD

**Issue by anilabhadatta** [kaliiiiiiiiii/Selenium-Profiles#45]
```python
profile = profiles.Android()
mydriver = Chrome(
            profile, options=options, uc_driver=True,
            executable_path=f"./chromedrivers/chromedriver.exe")
if headless:
     mydriver.options.add_argument("--headless=new")
driver = mydriver.start()
```
This is my code to start the browser in headless mode but it is not working, In Non headless mode the code is working as expected.
```
Error: '<' not supported between instances of 'NoneType' and 'int'
```
As of now i know that i am getting this error when i am using `uc_driver=True`.
There is a bug in official undetected_chromedriver where i need to write the following  code to initiate chrome as headless mode using UC driver.
```python
driver = ucdriver.Chrome(headless=headless,  version_main=112,
                                 options=options, driver_executable_path=f"./chromedrivers/chromedriver.exe")
```
I need to put `version_main` and `headless=True` so that chrome can load in headless mode using ucdriver. If i didn't apply version_main as parameter then i was receiving the same error.

Can you add headless and version_main to your selenium_profiles so that ucdriver can load properly?

**Comment by anilabhadatta** [comment]
I have made a fix, willing to share with you.

**Comment by kaliiiiiiiiii** [comment]
Thanks for submitting this issue.
I've thought from the beginning on about passing the arguments directly to undetected-chromedriver, but assumed it should also work without, as he checks at [undetected_chromedriver/__init__.py#L290](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/bf7dcf8b5713020de7454844fb80036b8c456503/undetected_chromedriver/__init__.py#L290) for the `--headless` key. Wonder what exactly caused this bug.

I'll have a look in the.. probably next days :)

**Comment by kaliiiiiiiiii** [comment]
Yeah thought about something like that.
Althought I'd preferably not add 2 arguments to my driver just for fixing a bug in undetected-chromedriver:)

I guess I'll add automatic detection for the Chrome version and headless options, since we don't want any inconsistencies👀

**Comment by anilabhadatta** [comment]
@kaliiiiiiiiii yes that would be better, i think getting chrome version will he be easy. Maybe using os library you can probably call the chrome at specific or default path and pass a parameter as version, which may return the version of chrome.

As for headless mode you are already taking headless mode as chromeoptions so that can be implemented easily in yout init.py

**Comment by kaliiiiiiiiii** [comment]
> getting chrome version will he be easy.

Uhh not as easy as thought:)
On linux, `chrome --version` works cleanly, but Windows has some hard times:

- `chrome.exe`  includes the version at some point, but reading & parsing those files takes up processing power, time, and RAM -_-
- getting some REGISTRY key works as well.

Isssue with those: Probably not reliable

**Comment by paamayim** [comment]
> On linux, `chrome --version` works cleanly, but Windows has some hard times:
> 
> * `chrome.exe`  includes the version at some point, but reading & parsing those files takes up processing power, time, and RAM -_-
> * getting some REGISTRY key works as well.

It looks like that's what [chromedriver-autoinstaller](https://github.com/yeongbin-jo/python-chromedriver-autoinstaller/tree/master) did [here](https://github.com/yeongbin-jo/python-chromedriver-autoinstaller/blob/1132054214b1986a61b488e286957b8bdc962079/chromedriver_autoinstaller/utils.py#LL103C19-L103C19)

```python
import chromedriver_autoinstaller

version_main = int(chromedriver_autoinstaller.get_chrome_version().split(".")[0])
this.driver = webdriveruc.Chrome(options=options, seleniumwire_options=seleniumwire_options, version_main=version_main)
```

**Comment by kaliiiiiiiiii** [comment]
> It looks like that's what [chromedriver-autoinstaller](https://github.com/yeongbin-jo/python-chromedriver-autoinstaller/tree/master) did [here](https://github.com/yeongbin-jo/python-chromedriver-autoinstaller/blob/1132054214b1986a61b488e286957b8bdc962079/chromedriver_autoinstaller/utils.py#LL103C19-L103C19)
> 
> ```python
> import chromedriver_autoinstaller
> 
> version_main = int(chromedriver_autoinstaller.get_chrome_version().split(".")[0])
> this.driver = webdriveruc.Chrome(options=options, seleniumwire_options=seleniumwire_options, version_main=version_main)
> ```
@paamayim Thanks a lot! Didn't test it yet, but looks great

I might copy only the `get_chrome_version()` function and put some credits in there for implementation.

**Comment by kaliiiiiiiiii** [comment]
fix seems to be indended by undetected-chromedriver (see [commit](https://github.com/ultrafunkamsterdam/undetected-chromedriver/commit/46b000ae2123059f37fdb70bbe390b9b8a62df5b#) )
closing therefore
