### ISSUE TITLE
Devtools Runtime detection

### ISSUE THREAD

**Issue by xAffan** [kaliiiiiiiiii/Selenium-Profiles#57]
**Describe the bug**
Falix.gg detects the chromedriver, and subsequently redirects you to about:blank.

**To Reproduce**
```py
from selenium_profiles.webdriver import Chrome
from selenium_profiles.profiles import profiles
from selenium.webdriver.common.by import By  # locate elements
from selenium.webdriver import ChromeOptions


profile = profiles.Windows()
options = ChromeOptions()
mydriver = Chrome(profile, options=options, uc_driver=False)
# mydriver.options.add_argument("--headless=new")

driver = mydriver.start()

# get url
driver.get('https://falix.gg/?id=12345678')  # test fingerprint

input("Press ENTER to exit: ")
driver.quit()  # Execute on the End!
```

**Expected behavior or error-message**
There should not have been a redirect to about:blank. You can verify the behavior of the site by visiting normally.

**Environment (please complete the following information):**
 - OS: Arch Linux
- OS-Version Latest
- Browser Chromium
 - Selenium-Profiles Version 2.2.5.1

**Additional context**
I would like to add that the website detects dev tools and redirects you. I think detecting dev tools correlates to detecting Chromedriver.

**Comment by kaliiiiiiiiii** [comment]
merge to https://github.com/kaliiiiiiiiii/Selenium-Profiles/discussions/44
And yes, it is correlated to the devtools. Currently  no solution, but working on it:)

Thanks a lot for your nice

**Comment by xAffan** [comment]
Definitely waiting desperately for some solution. Undetected chromedriver's solution was to ditch chromedriver (soon) Check discussion https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1321#issuecomment-1582188178

**Comment by kaliiiiiiiiii** [comment]
> Definitely waiting desperately for some solution. Undetected chromedriver's solution was to ditch chromedriver (soon) Check discussion [ultrafunkamsterdam/undetected-chromedriver#1321 (comment)](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1321#issuecomment-1582188178)

oh that's interesting. Wonder what's happening in the background//how it works

**Comment by xAffan** [comment]
Do u plan on working for a solution tho or is it on stall rn?

**Comment by kaliiiiiiiiii** [comment]
```python
driver.execute_cdp_cmd("Runtime.disable",{})
driver.get('https://falix.gg/?id=12345678')
```
fixes this issue for me. Not sure if it has any sidefeccts tho.
see [Runtime.disable](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-removeScriptToEvaluateOnLoad) for documentation

**Comment by xAffan** [comment]
script execution may not matter much but find element and click are crucial for selenium app. That being said, this still is huge progress 🥳

**Comment by kaliiiiiiiiii** [comment]
> ```python
> driver.execute_cdp_cmd("Runtime.disable",{})
> driver.get('https://falix.gg/?id=12345678')
> ```
> 
> fixes this issue for me. But causes some problems:
> 
> * find element doesn't work
> * click doesn't work
> * script execution doesn't work
> 
> see [Runtime.disable](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-removeScriptToEvaluateOnLoad) for documentation

there might be a way to automate chrome using a remote-controlled chrome-extension
status:working on ( see https://github.com/kaliiiiiiiiii/Selenium-Injector)

**Comment by kaliiiiiiiiii** [comment]
@xAffan I'd like to do further tests on that, but unfortanely, the website seems down (ERR_CONNECTION_TIMED_OUT).

Any other sites I could use for that?

**Comment by NCLnclNCL** [comment]
> > ```python
> > driver.execute_cdp_cmd("Runtime.disable",{})
> > driver.get('https://falix.gg/?id=12345678')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > fixes this issue for me. But causes some problems:
> > 
> > * find element doesn't work
> > * click doesn't work
> > * script execution doesn't work
> > 
> > see [Runtime.disable](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-removeScriptToEvaluateOnLoad) for documentation
> 
> there might be a way to automate chrome using a remote-controlled chrome-extension status:working on ( see https://github.com/kaliiiiiiiiii/Selenium-Injector)

i dont like extension

**Comment by kaliiiiiiiiii** [comment]
### with selenium-driverless
warning: 
- this package is experimental and might include bugs, please report them at [bug-reports](https://github.com/kaliiiiiiiiii/Selenium-Driverless/issues)
- only for python >=3.8
- you'll need to install __pycdp__ first with `pip install git+https://github.com/HMaker/python-cdp.git@latest`
```python
from selenium_profiles.webdriver import Chrome
from selenium_profiles.profiles import profiles
from selenium_driverless.webdriver import ChromeOptions
from selenium_driverless.types.by import By

profile = profiles.Windows()  # or .Android
options = ChromeOptions()
# options.add_argument("--headless=new")
driver = Chrome(profile, options=options, driverless_options=True)

# get url
driver.get('https://nowsecure.nl#relax')  # test fingerprint

driver.quit()  # Execute on the End!
```
see [documentation](https://github.com/kaliiiiiiiiii/Selenium-Driverless) for usages

**Comment by Bengrove20011** [comment]
@kaliiiiiiiiii please can you contact me regards to work email info@cashmakeruk.com
