### ISSUE TITLE
Unable to make POST request via fetch()

### ISSUE THREAD

**Issue by Deimmm** [kaliiiiiiiiii/Selenium-Profiles#88]
Little typo, missing cloumn in methods list.
fix: https://github.com/kaliiiiiiiiii/Selenium-Profiles/commit/4665e0848b8884bfde8b09c6df7159d264e44bb7

**Comment by kaliiiiiiiiii** [comment]
@Deimmm 
yep, my bad. I'll implement it in the next version. Thanks for submitting this issue
