### ISSUE TITLE
Bug when starting

### ISSUE THREAD

**Issue by AlexPaiva** [kaliiiiiiiiii/Selenium-Profiles#92]
Starting the basic example code from the main github page or any code (using the driver obviously) I get this:
```
C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium_driverless\sync\switch_to.py:12: RuntimeWarning: coroutine 'SwitchTo._init' was never awaited
  self._init()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

What could be wrong?

**Environment (please complete the following information):**
- OS: Windows
- OS-Version 10
- Browser Latest Chrome
- Selenium-Profiles Version Latest
- Python version 3.10.5

**Comment by kaliiiiiiiiii** [comment]
dublicate https://github.com/kaliiiiiiiiii/Selenium-Driverless/issues/27#event-10094353305, thanks for opening this issue, will be fixed soon
