### ISSUE TITLE
unpack extentions are not loading.

### ISSUE THREAD

**Issue by Mehranali669** [kaliiiiiiiiii/Selenium-Profiles#99]
**unpack extentions are not loading **
i was using this but in my case i want to load some unpack extention these extentions are not loading in driver.
i have tried such things but nothing is working in chrome 116

**code i have tried**
```
#options.add_argument(f"--load-extension={profile['extentions']}");
options.add_argument(f"load-extension={profile['extentions']}");
options.add_extension(f"--load-extension={profile['extentions']}");
```

**Comment by kaliiiiiiiiii** [comment]
please provide the full code you used including the path to the extension you want to add

**Comment by Mehranali669** [comment]
this is the code i was running. also when i use uc_driver=True it wont work the chrome is like its crash or some thing

`
from selenium_profiles.webdriver import Chrome
from selenium_profiles.profiles import profiles
from seleniumwire import webdriver


profilenew = profiles.Windows() # or .Android
options = webdriver.ChromeOptions()

options.add_extension(r"C:\Users\MehranAli\Desktop\moto\webAuto\extentions\emptyProxy");
options.add_argument(r"--load-extension=C:\Users\MehranAli\Desktop\moto\webAuto\extentions\emptyProxy");
options.add_argument(r"load-extension=C:\Users\MehranAli\Desktop\moto\webAuto\extentions\emptyProxy");


driver = Chrome(profilenew, options=options,uc_driver=False, seleniumwire_options=True)
# get url
driver.get('https://google.com/')  # test fingerprint

input("Press ENTER to exit: ")`

**Comment by kaliiiiiiiiii** [comment]
- for `.crx` or `.zip` files
```python
options.add_extension(r"C:/some_path/extension.crx")
```
- for a extracted extension
```python
options.add_argument(r"--load-extension=C:/some_path/extension")
```

1. What error do you get with `uc_driver=True` ?
2. What happens when adding a extension? Does it just ignore it, or is there any error?
3. Does something like the following work?
```python
profile["options"]["extension_paths"] = ["C:/some_path/extension"]
```
